### ISSUE TITLE
Any plan to support Android?

### ISSUE THREAD

**Issue by sy-tang** [kennycason/kumo#19] opened 2015-12-01 15:20 UTC

**Comment by kennycason** [comment] 2016-01-18 22:56
What's needed specifically? It's in Java and has an interface for BufferedImages. I'm not familiar with what is required to make it work for Android. :)

**Comment by kennycason** [comment] 2018-08-17 18:31
going to mark as duplicate of #49, only because #49 has more commentary on it.

**Closed by kennycason** 2018-08-17 18:31 UTC
